;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; DO NOT EDIT THIS FILE.
;
; Your changes to this file will be overwritten by ServerPilot.
;
; For information on how to customize php settings, see
; https://serverpilot.io/community/articles/customize-php-settings.html
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

pm = ondemand
pm.max_children = 20
